	<div id="footer-wrapper" class="fixed-footer">
		<footer>
	        <div class="container-fluid">
	        	<div class="row">
		        	<div class="col-md-3 first-col">
		        		<!-- <h1>Our Resorts</h1> -->
		        		<img src="images/logo/footer-logo.png" class="img-responsive" alt="footer logo">
		        		<ul>
		        			<li>
		        				<h3>Nongsa, Batam</h3>
		        				<p>Indonesia</p>
		        			</li>
		        			<li>
		        				<h3>Seminyak, Bali</h3>
		        				<p>Indonesia</p>
		        			</li>
		        		</ul>
		        	</div>	     
		        	<div class="col-md-3 second-col">
		        		<h1>Explore</h1>
		        		<h2>Categories</h2>
		        		<ul>
		        			<li><a href="#">About</a></li>
		        			<li><a href="#">accomodation</a></li>
		        			<li><a href="#">dining</a></li>
		        			<li><a href="#">experiences</a></li>
		        			<li><a href="#">events</a></li>
		        			<li><a href="#">amenities</a></li>
		        			<li><a href="#">faq</a></li>
		        			<li><a href="#">contact us</a></li>
		        		</ul>
		        	</div>
		        	<div class="col-md-3 third-col">
		        		<h1>Sign Up</h1>
		        		<h2>Newsletter</h2>
		        		<p>Be the first to know about Montigo Resorts exclusive perks, events and promotions!</p>
		        		<div class="subscribe-form">
		        			<input type="email" name="email" placeholder="Enter your email here..." />
		        			<div class="link-container">
		        				<a href="#" class="link-to"><i class="fa fa-chevron-right"></i></a>
		        			</div>
		        		</div>
		        	</div>
		        	<div class="col-md-3 fourth-col">
		        		<h1>follow Us</h1>
		        		<h2>Instagram</h2>
		        		<ul>
		        			<li><a href="#"><img src="images/content/instagram-1.png" alt=""></a></li>
		        			<li><a href="#"><img src="images/content/instagram-2.png" alt=""></a></li>
		        		</ul>
		        		<ul>
		        			<li><a href="#" class="facebook"><i class="fa fa-facebook"></i></a></li>
		        			<li><a href="#" class="twitter"><i class="fa fa-twitter"></i></a></li>
		        		</ul>
		        	</div>
	        	</div>
	        </div>
      	</footer>
	</div>
	<div id="copyright-wrapper" class="fixed-footer">
		<div class="container-fluid">
			<div class="row">
				<div class="col-md-12">
					<ul>
						<li><a href="#">montigo resorts</a></li>
						<li><a href="#">sitemap</a></li>
						<li><a href="#">careers</a></li>
						<li><a href="#">Terms of Use</a></li>
						<li><a href="#">Privacy Policy</a></li>
					</ul>		
					<p>Copyright © 2014 Montigo Resorts. All rights reserved.</p>			
				</div>
			</div>			
		</div>
	</div>
</div><!-- page wrapper end -->