<div id="page-wrapper">
	<div id="header-wrapper">
		<header id="main-header" class="container-fluid">
			<div class="row">
				<div id="logo-container" class="col-md-2">
					<a href="index.html" class="logo"><img src="images/logo/main-logo.png" alt="main logo"></a>
				</div>
				<div id="menu-container" class="col-md-7 col-md-offset-3">
					<nav class="main-menu">
						<ul>
							<li><a href="#">about</a></li>
							<li><a href="#">accomodation</a></li>
							<li><a href="#">dining</a></li>
							<li><a href="#">experiences</a></li>
							<li><a href="#">events</a></li>
							<li><a href="#">amenities</a></li>
							<li><a href="#">faq</a></li>
							<li><a href="#">contact us</a></li>
						</ul>
					</nav>
				</div>
			</div>
		</header>
	</div>
