<!-- Mobile Viewport -->
<meta name="viewport" content="width=device-width, initial-scale=1.0" />

<!-- Force IE to render best possible view -->
<meta http-equiv="X-UA-Compatible" content="IE=edge" />

<!-- FONT -->
<script src="//use.typekit.net/avg1jpg.js"></script>
<script>try{Typekit.load();}catch(e){}</script>

<!-- CSS -->
<link rel="stylesheet" href="css/vendors/bootstrap/bootstrap.min.css" />
<link rel="stylesheet" href="css/vendors/bootstrap/bootstrap-theme.min.css" />
<link rel="stylesheet" href="css/font-awesome.min.css" />
<link rel="stylesheet" href="css/normalize.css" />
<link rel="stylesheet" href="css/style.css" />

<!-- JS -->
<script type="text/javascript" src="js/vendors/jquery/jquery-1.11.1.min.js"></script>
<script type="text/javascript" src="js/vendors/bootstrap/bootstrap.min.js"></script>
<script type="text/javascript" src="js/vendors/modernizr-2.7.1.min.js"></script>
<script type="text/javascript" src="js/plugins/jquery.waypoints.min.js"></script>
<script type="text/javascript" src="js/plugins/jquery.bgswitcher.js"></script>
<script type="text/javascript" src="js/plugins/jquery.nicescroll.min.js"></script>
<!-- <script type="text/javascript" src="js/plugins/imagesloaded.js"></script> -->
<!-- <script type="text/javascript" src="js/plugins/skrollr.js"></script> -->
<script type="text/javascript" src="js/main.js"></script>
<!-- <script type="text/javascript" src="js/_main.js"></script> -->