<div id="page-wrapper">
	<div id="header-wrapper">
		<header id="main-header" class="container-fluid">
			<div class="row">
				<div class="col-md-12">
					<div id="logo-container">
						<a href="index.html" class="logo"></a>
					</div>
					<div id="menu-container">
						<nav class="main-menu">
							<ul>
								<li><a href="#">about</a></li>
								<li><a href="#">accomodation</a></li>
								<li><a href="#">dining</a></li>
								<li><a href="#">experiences</a></li>
								<li><a href="#">events</a></li>
								<li><a href="#">amenities</a></li>
								<li><a href="#">faq</a></li>
								<li><a href="#">contact us</a></li>							
							</ul>
						</nav>
					</div>
				</div>
			</div>
		</header>
		<div class="cta-book"><a href="javascript:void(0);" id="book">book now</a></div>
		
		<div class="booking-form">

			<form action="" class="booking">
				<div class="inputs">
					<label for="arrival">Arrival</label>
					<div class="dropdown">
						<select name="arrival" id="arrival">
							<option value="">25 december 2015</option>
						</select>
					</div>
				</div>
				
				<div class="inputs">
					<label for="arrival">Departure</label>
					<div class="dropdown">
						<select name="arrival" id="arrival">
							<option value="">25 december 2015</option>
						</select>
					</div>
				</div>

				<div class="inputs small-inputs">
					<label for="villas">Villas</label>
					<div class="dropdown-2">
						<select name="villas" id="villas" class="small-input">
							<option value="0">0</option>
							<option value="1">1</option>
							<option value="2">2</option>
							<option value="3">3</option>
							<option value="4">4</option>
							<option value="5">5</option>
							<option value="6">6</option>
							<option value="7">7</option>
							<option value="8">8</option>
							<option value="9">9</option>
							<option value="10">10</option>
						</select>
					</div>
				</div>

				<div class="inputs small-inputs">
					<label for="adults">Adults</label>
					<div class="dropdown-2">
						<select name="adults" id="adults" class="small-input">
							<option value="0">0</option>
							<option value="1">1</option>
							<option value="2">2</option>
							<option value="3">3</option>
							<option value="4">4</option>
							<option value="5">5</option>
							<option value="6">6</option>
							<option value="7">7</option>
							<option value="8">8</option>
							<option value="9">9</option>
							<option value="10">10</option>
						</select>
					</div>
				</div>

				<div class="inputs small-inputs">
					<label for="children">Children</label>
					<div class="dropdown-2">
						<select name="children" id="children" class="small-input">
							<option value="0">0</option>
							<option value="1">1</option>
							<option value="2">2</option>
							<option value="3">3</option>
							<option value="4">4</option>
							<option value="5">5</option>
							<option value="6">6</option>
							<option value="7">7</option>
							<option value="8">8</option>
							<option value="9">9</option>
							<option value="10">10</option>
						</select>
					</div>
				</div>

				<div class="inputs">
					<label for="code">Code</label>
					<input type="text" name="code">
				</div>

				<div class="inputs btn-container">
					<a href="#" id="find-villa-btn">FIND A VILLA <i class="fa fa-chevron-right"></i></a>
				</div>
			</form>

			
		</div>
	</div>
