<div id="carousel" class="slider-wrapper carousel slide" data-ride="carousel">

	<!-- Wrapper for slides -->
	<div class="carousel-inner">
		<div class="item bg bg1 active">
			<div class="carousel-caption">
				<div class="caption-text">
					<h1>LOREM IPSUM</h1>					
				</div>
			</div>				
		</div>
	</div>

	<a href="#content-wrapper" class="scroll-to-content"><div class="arrow bounce"></div></a>
</div>
